
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BaigMedicalStore.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OrderDetail
{

    public long OrderDetailId { get; set; }

    public long OrderId { get; set; }

    public int ItemId { get; set; }

    public Nullable<int> Quantity { get; set; }



    public virtual Order Order { get; set; }

    public virtual Item Item { get; set; }

}

}
